### ISSUE TITLE
Break installation tasks into separate plays

### ISSUE THREAD

**Issue by electricallen** [electricallen/nextcloud-ansible#2]
Since there are two installation strategies (>= 20.04 and < 20.04) these should get broken into separate plays using ansible `include` - EG

```YAML
- name: Install on newer versions 
   include: Install2004.yaml
   when: ansible_distribution_version is version('20.04', '>=')

- name: Install on older versions 
   include: Install1804.yaml
   when: ansible_distribution_version is version('20.04', '<')
  
  ```
