### ISSUE TITLE
Integrate missing indices command

### ISSUE THREAD

**Issue by electricallen** [electricallen/nextcloud-ansible#8]
Using a return code, I think this can be state based, EG:

```yaml
  - shell:
      cmd: docker-compose exec --user www-data nextcloud php occ db:add-missing-indices
      chdir: ~/nextcloud/
    register: nextcloud_indices
    changed_when: nextcloud_indices.rc != 0
```
